# config/serializer/Videojocs.yaml
App\Entity\Videojoc:
    attributes:
        id:
            groups: ["videojocs"]
        titol:
            groups: ["videojocs"]
        portada:
            groups: ["videojocs"]
        resena:
            groups: ["videojocs"]
        preu:
            groups: ["videojocs"]
        cantitat:
            groups: ["videojocs"]
        dataCreacio:
            groups: ["videojocs"]
        genere:
            groups: ["videojocs"]
        plataformas:
             groups: ['videojocs']
